version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "swift"
    directory: "/FirstTaskDependencies"
    schedule:
      interval: "weekly"
      day: "friday"
      timezone: "Asia/Tokyo"
