excluded:
  - vendor
  - "**/.build"

disabled_rules:
  - multiple_closures_with_trailing_closure
  - trailing_comma # covered-by swift-format

line_length:
  warning: 200
  error: 300

identifier_name:
  min_length:
    warning: 1

