default_platform(:ios)

platform :ios do

  private_lane :import_certificates_and_provisioning_profile do
    create_keychain(
        name: "ios_app_keychain",
        password: ENV["KEYCHAIN_PASSWORD"],
        timeout: 1800
    )
    import_certificate(
        certificate_path: "distribution.p12",
        certificate_password: ENV["CERTIFICATE_PASSWORD"],
        keychain_name: "ios_app_keychain",
        keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )
    install_provisioning_profile(path: "distribution.mobileprovision")
  end

  desc "Submit a new Beta Build to DeployGate"
  lane :dg do
    import_certificates_and_provisioning_profile
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "FirstTask.xcodeproj",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: "org.codefirst.FirstTask",
      profile_name: "FirstTask Deploygate Adhoc deployment"
    )
    update_project_team(
      path: 'FirstTask.xcodeproj',
      teamid: ENV['TEAM_ID'])
    build_app(
      scheme: 'FirstTask',
      export_options: {
        method: 'ad-hoc'
      }
    )
    deploygate(
      api_token: ENV['DEPLOYGATE_API_KEY'],
      user: ENV['DEPLOYGATE_USER'],
      message: ENV['DEPLOYGATE_MESSAGE'] || 'Build')
    update_project_team(
      path: 'FirstTask.xcodeproj',
      teamid: '')
  end

  desc "Build for simulator"
  lane :build_for_simulator do
    xcbuild(
      workspace: "FirstTask.xcworkspace",
      scheme: "FirstTask",
      configuration: "Debug",
      xcargs: "-sdk iphonesimulator"
    )
  end
end

