name: Deploy

on:
 push:
   branches: [ master ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.1.app/Contents/Developer

jobs:
 build:

   runs-on: macos-latest

   steps:
   - uses: actions/checkout@v2

   - name: Setup LicensePlist
     run: curl -fsSL https://raw.githubusercontent.com/mono0926/LicensePlist/master/install.sh | sh

   - name: Setup p12 certificate file
     run: |
       echo "${{ secrets.CERTIFICATE }}" > distribution.p12.txt
       base64 --decode distribution.p12.txt > distribution.p12

   - name: Setup provisioning profile
     run: |
       echo "${{ secrets.PROVISIONING_PROFILE }}" > distribution.mobileprovision.txt
       base64 --decode distribution.mobileprovision.txt > distribution.mobileprovision

   - name: Cache Gems
     uses: actions/cache@v2
     with:
       path: vendor/bundle
       key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
       restore-keys: |
         ${{ runner.os }}-gems-

   - name: Install Bundled Gems
     run: |
       bundle config path vendor/bundle
       bundle install --jobs 4 --retry 3

   - name: Cache Pods
     uses: actions/cache@v2
     with:
       path: Pods
       key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
       restore-keys: |
         ${{ runner.os }}-pods-

   - name: Install Pods
     run: bundle exec pod install

   - name: Build and deploy to DeployGate
     env:
       TEAM_ID: ${{ secrets.TEAM_ID }}
       DEPLOYGATE_API_KEY: ${{ secrets.DEPLOYGATE_API_KEY }}
       DEPLOYGATE_USER: ${{ secrets.DEPLOYGATE_USER }}
       KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
       CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
     run: bundle exec fastlane dg
